# Numpy Module

In [381]:
import numpy as np

### Create Simple Arrays

In [382]:
a = np.array([1,2,3]) # 1-d array
b = np.array([[1,2,3],[4,5,6]]) # 2-d array

### Array Properties

In [383]:
a.ndim, b.ndim

(1, 2)

In [384]:
a.shape, b.shape

((3,), (2, 3))

In [385]:
# number of elements in array
a.size, b.size

(3, 6)

In [386]:
# size of single item
a.itemsize 

8

In [387]:
# total size
a.nbytes

24

In [388]:
a.itemsize * a.size

24

In [389]:
b.itemsize * b.size

48

### Accessing / Changing specific elements, row, columns, etc

In [390]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]]) # 2-d array


In [391]:
# Get a specific element
a[0, 5]

np.int64(6)

In [392]:
# Get an element from a specific row
a[0, :] 

# select 0th row and get everything in the column

array([1, 2, 3, 4, 5, 6])

In [393]:
# Get an element from a specific col
a[:, 0] 

# select every row ad get 0th column

array([1, 7])

In [394]:
# Step Size can also be used
a[0, ::2]

array([1, 3, 5])

In [395]:
# Changig a Single Value
a[0,0] = -5  

a

array([[-5,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [396]:
# Changig an Entire Row
a[0,:] = [0,1,2,3,4,5]  

a

# Meaning we can replace as long as 

array([[ 0,  1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11, 12]])

### Initializing different types of Array

In [397]:
# Zero Matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [398]:
np.zeros([2,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [399]:
# Ones Matrix
np.ones(5)

array([1., 1., 1., 1., 1.])

In [400]:
np.ones([2,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [401]:
# Array with number of My Choice
np.full([2,2], 99)

array([[99, 99],
       [99, 99]])

In [402]:
# Array with Random Float Numbers
np.random.rand(4,2)

array([[0.15319314, 0.67997714],
       [0.76728327, 0.83446139],
       [0.16703507, 0.8873366 ],
       [0.5153397 , 0.86194825]])

In [403]:
# Array with Random Integers
#(range, size)
np.random.randint(7, size=(3,3)) # 7 is exclusive 

array([[0, 0, 5],
       [1, 6, 3],
       [6, 2, 3]])

In [404]:
np.random.randint(1, 5, size=(3,3)) # adjusting low and high parameters

array([[2, 4, 1],
       [1, 2, 4],
       [2, 4, 2]])

In [405]:
# Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Copying Arrays (Be Careful)

In [406]:
a = np.array([1,2,3])

In [407]:
b = a

In [408]:
b[0] = -9

In [409]:
a, b

(array([-9,  2,  3]), array([-9,  2,  3]))

both the arrays changed even tough we just altered the value of b !

hence we use **.copy()** method

In [410]:
a = np.array([1,2,3])

In [411]:
b = a.copy()

In [412]:
b[0] = -6

In [413]:
a, b

(array([1, 2, 3]), array([-6,  2,  3]))

now only one the 0th index in b is changed 

### Basic Mathematics

In [414]:
a = np.array([1,2,3])

In [415]:
a + 2

array([3, 4, 5])

In [416]:
a - 2

array([-1,  0,  1])

In [417]:
a * 2

array([2, 4, 6])

In [418]:
a / 2

array([0.5, 1. , 1.5])

In [419]:
a % 2

array([1, 0, 1])

In [420]:
a = np.array([1,2,3])
b = np.array([3,2,1])

In [421]:
a + b

array([4, 4, 4])

In [422]:
a - b

array([-2,  0,  2])

In [423]:
a * b

array([3, 4, 3])

In [424]:
a // b

array([0, 1, 3])

In [425]:
np.sin(a), np.cos(a), np.tan(a)

(array([0.84147098, 0.90929743, 0.14112001]),
 array([ 0.54030231, -0.41614684, -0.9899925 ]),
 array([ 1.55740772, -2.18503986, -0.14254654]))

### Linear Algebra

#### Matrix Multiply

In [426]:
a = np.full([2, 3], 2)
a

array([[2, 2, 2],
       [2, 2, 2]])

In [427]:
b = np.full([3, 2], 3)
b

array([[3, 3],
       [3, 3],
       [3, 3]])

we cannot directly multiple a and b since their shapes are different

In [428]:
a * b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

but we know that if inner dimensions match we ca multiple two arrays  
we can do that by using matrix multiplication function **matmul()**

In [237]:
np.matmul(a, b)

array([[18, 18],
       [18, 18]])

#### Matrix Determinant 

In [239]:
c = np.identity(3)
np.linalg.det(c) # determinant of  identity matrix is 1


np.float64(1.0)

### Statistics

In [240]:
stats = np.array([[1,2,3],[4,5,6]])

In [241]:
np.min(stats)

np.int64(1)

In [245]:
np.max(stats)

np.int64(6)

In [246]:
## Min Max for Row or Col

np.min(stats, axis=0) # minimum row

array([1, 4])

In [247]:
np.min(stats, axis=1) # minimum col

array([1, 4])

In [248]:
np.sum(stats)

np.int64(21)

### Reorganizing Arrays

In [ ]:
# ReShaping
before = np.array([1,2,3,4,5,6])

In [252]:
before.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [253]:
before.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [257]:
# Vertically Stacking the Arrays

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack((v1, v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [258]:
# Horizontally Stacking the Arrays

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.hstack([v1, v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

### Random Module

#### 1. Random Sampling

2 x 4 Matrix With Random Values

In [261]:
np.random.rand(2,4)

array([[0.08099714, 0.08273402, 0.90591982, 0.08235042],
       [0.4063079 , 0.62099845, 0.05121704, 0.68506811]])

2 x 4 Matrix with Random Values from Standard Normal Distribution


In [310]:
np.random.randn(2, 4)

array([[ 0.67635211,  0.37864239,  0.40988025,  0.1607241 ],
       [-0.00557487,  1.9711143 , -1.94461029,  0.486401  ]])

Generates random integers between low (inclusive) and high (exclusive)

In [311]:
np.random.randint(low=0, high=11, size=((2, 2)))

array([[ 8,  1],
       [ 4, 10]])

#### 2. Permutations

Randomly permute a sequence

In [364]:
arr = np.array([1, 2, 3, 4, 5])

np.random.permutation(arr)

[2 3 5 4 1]


Shuffle the contents of an array in-place

In [366]:
np.random.shuffle(arr)

arr

array([5, 4, 2, 1, 3])

Generate a random sample from a given array or range

In [367]:
np.random.choice([10,20,30], size=5, replace=True)

array([20, 30, 10, 20, 30])

In [371]:
np.random.choice(150, size=3, replace=True)

array([65, 44, 24])

eg: pick random samples from stacked array

In [374]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

stacked = np.vstack((v1, v2, v2, v1, v2))
stacked

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [376]:
stacked.shape[0]

5

In [379]:
random_idx = np.random.choice(stacked.shape[0], size=2, replace=True)
random_idx

array([1, 0])

In [380]:
stacked[random_idx]

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])